### ISSUE TITLE
Error: Function called outside component initialization when using createEventDispatcher()

### ISSUE THREAD

**Issue by JonRaph** [rafalou38/svelte-preview#22]
**Describe the bug**
When using
```javascript
    import { createEventDispatcher } from 'svelte';
    const dispatch = createEventDispatcher();
```
the preview does not render.

```
Error: Function called outside component initialization
    at get_current_component (/.vscode/extensions/rafaelmartinez.svelte-preview-2.7.1/node_modules/svelte/internal/index.mjs:986:15)
    at createEventDispatcher (/.vscode/extensions/rafaelmartinez.svelte-preview-2.7.1/node_modules/svelte/internal/index.mjs:1043:23)
    at instance (/test.svelte:154:19)
    at init (/.vscode/extensions/rafaelmartinez.svelte-preview-2.7.1/media/svelte.js:2111:7)
    at new Component (/test.svelte:164:3)
    at /test.svelte:168:5
```

**To Reproduce**
Add the following two lines to any svelte file:
```javascript
    import { createEventDispatcher } from 'svelte';
    const dispatch = createEventDispatcher();
```

**Expected behavior**
A normal render.

**Version:**
2.7.1

**Additional context**
I read it is a 'known bug' in the extension's docs. Maybe it will get fixed, or there is a way to circumvent the error message.

**Comment by JonRaph** [comment]
I found a temporary solution with code from here: https://stackoverflow.com/a/66985113
```javascript
    // Hack for svelte-preview.
    // Uncomment the first line and remove the 'import get_current_component' line and function in production.
    //import { createEventDispatcher } from 'svelte'
    import { get_current_component } from "svelte/internal";
    function createEventDispatcher() {
        const component = get_current_component();
        return (type, target, detail) => {
            const callbacks = component.$$.callbacks[type];
            if (callbacks) {
                if (target.dispatchEvent) {
                    const event = new CustomEvent(type, { detail });
                    // the key is to call `dispatchEvent` manually to set `event.target`
                    target.dispatchEvent(event);
                    callbacks.slice().forEach((fn) => {
                        fn.call(component, event);
                    });
                }
            }
        };
    }
```

**Comment by JonRaph** [comment]
Don't know exactly why, but it works now without the hack directly with

```javascript
    import { createEventDispatcher } from 'svelte';
```

Strange...
